### ISSUE TITLE
asio error when importing

### ISSUE THREAD

**Issue by anoadragon453** [rllola/zeronet-torrent-plugin#11]
I downloaded the Linux build and put the contents of the .zip file into my `plugins/Torrent` folder. Upon starting ZeroNet I'm met with the following error:

```
PluginManager Plugin Torrent load error: RuntimeError: context: asio.ssl error in PluginManager.py line 50 > builtins.py line 96 > __init__.py line 1 > builtins.py line 96 > TorrentPlugin.py line 21 > TorrentPlugin.py line 24
```

The test page reports the plugin is not installed.

**Comment by rllola** [comment]
It is the first time I see this error. 
Can you tell me which version of Zeronet you have and what distro of linux you have ? Also I have only build for 64bit arch.

**Comment by rllola** [comment]
I also have this error...
I am going to look at it but you can attempt to build it with conan directly on your machine. It should work.

**Comment by rllola** [comment]
Ok !
It should be fix in this release https://github.com/rllola/zeronet-torrent-plugin/releases/tag/v0.1.1

**Comment by anoadragon453** [comment]
Great!
