### ISSUE TITLE
How does it works? README.md doesn't explains it well

### ISSUE THREAD

**Issue by danimesq** [rllola/zeronet-torrent-plugin#26]
Can a user download a existing torrent by putting its magned URL in a ZN site field? Also, can ZN files get their torrent magnet to be downloaded in BitTorrent clients?

**Comment by danimesq** [comment]
@rllola

**Comment by rllola** [comment]
It is a bittorrent client embedded in a ZeroNet plugin. Yes, you can download torrent by using a magnet or a torrent file. It will also seed the torrent (like for any bittorrent client).

I am about to release the new version! I will try to put more information on the README.md

you can also visit the website : http://127.0.0.1:43111/1ChMNjXpW5vU5iXb9DSXzqAUfY46Pc2RTL/

You can download the plugin from their and test if it works on the site.

**Comment by slrslr** [comment]
The README and http://127.0.0.1:43110/1ChMNjXpW5vU5iXb9DSXzqAUfY46Pc2RTL/ does not explain benefits or examples of usage when one enable this plugin.

**Comment by rllola** [comment]
I have updated the README. Feel free to complete it.

**Comment by slrslr** [comment]
@rllola 

> I have updated the README

_"allow adding torrent files, hash or magnet"_ - it is missing explanation where/how and how these files will be accessible in Zeronet.

_"The files will be saved in the site folder which makes it available to the site."_ - so it adds somewhere some interface to add torrent file to the site of my choice? I am unable to see it. When i click some torrent file on someones site ([example this one](http://127.0.0.1:43110/185oen3LMinT9hmZo34b7DAim6h7Ja2Dki/)), then it does not load any interface. There is no guide on how to "makes it available to the site"

To your site http://127.0.0.1:43110/1ChMNjXpW5vU5iXb9DSXzqAUfY46Pc2RTL/ may be handy to add link under Install button to http://127.0.0.1:43110/Plugins/ so user knows how to disable plugin.

_"It also allows streaming video files out of the box."_ - You mean i source the torrent or magnet in the site html or js code somehow and then the zeronet will connect that torrent and use this torrent payload files as another sources and eventually download these files as a regular files to the site directory of the peer?Would be handy if your README is more descriptive and examples
